### PR TITLE
Reference to latest available issues

### PR DESCRIPTION
**Pull request by veelenga**
Not sure that this is a good idea to change a reference to the latest issue every week. As for me, that's much better just to link to the list of latest issues. I suppose campaign archive will show only some number of latest issues on [this](http://us11.campaign-archive1.com/home/?u=d644228761eb9a81e877365cc&id=764dae5f03) page. 

Unfortunately, that url is not shortened with [EepURL](http://eepurl.com/).

### CODE REVIEW

**Comment by sdogruyol** [comment]
Hey @veelenga , thanks for the PR i'll check it in the evening

**Comment by veelenga** [comment]
Hey @sdogruyol. No problem :-)

**Comment by veelenga** [comment]
Hey @sdogruyol, any update ?

**Comment by sdogruyol** [comment]
Thanks :+1:

**Pull request merged**
